# Generated by Django 6.0 on 2026-01-11 17:10

from django.db import migrations



def create_initial_data_currencies(apps, schema_editor):
    
    data_items = (
        {
            'title': 'Сербский динар',
            'code': 'RSD',
            'sort': 100,
        },
        {
            'title': 'Доллар США',
            'code': 'USD',
            'sort': 200,
        },
        {
            'title': 'Евро',
            'code': 'EUR',
            'sort': 300,
        },
        {
            'title': 'Рубль',
            'code': 'RUB',
            'sort': 400,
        },
    )

    Currencie = apps.get_model('my_saving', 'Currencie')
    sort = 0
    for item in data_items:
        sort +=100
        Currencie.objects.create(
            title=item['title'], 
            code=item['code'], 
            sort=sort,
            user=None
        )



def create_initial_data_expenses(apps, schema_editor):
    
    data_items = (
        {
            'title': 'Основные расходы/доходы',
            'description': 'Повседневный быт',
        },
    )

    Expense = apps.get_model('my_saving', 'Expense')
    sort = 0
    for item in data_items:
        sort +=100
        Expense.objects.create(
            title=item['title'], 
            description=item['description'], 
            sort=sort,
            user=None
        )
    

def create_initial_data_catrgories(apps, schema_editor):
    
    data_items = (
        {
            'title': 'Продукты',
            'description': 'Продукты питания',
        },
        {
            'title': 'Здоровье',
            'description': 'Расходы на здоровье',
        },
        {
            'title': 'Образование',
            'description': 'Расходы на Образование',
        },
        {
            'title': 'Транспорт',
            'description': 'Расходы на транспорт',
        },
    )

    Category = apps.get_model('my_saving', 'Category')
    sort = 0
    for item in data_items:
        sort +=100
        Category.objects.create(
            title=item['title'], 
            description=item['description'], 
            sort=sort,
            user=None
        )
        

        


    
    


class Migration(migrations.Migration):

    dependencies = [
        ('my_saving', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_initial_data_currencies),
        migrations.RunPython(create_initial_data_expenses),
        migrations.RunPython(create_initial_data_catrgories),
        
    ]
